from setuptools import setup, find_packages

setup(
    name='colorcompass',
    version='1.2.3',
    packages=find_packages(),
    install_requires=[],
    author='Nicolas Aguirre Campi',
    author_email='aguirrecampi.nicolas@gmail.com',
    description='Converts RGB or hexadecimal values to exact color names.',
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url='https://github.com/NicolasAguirreCampi/ColorCompass',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Scientific/Engineering :: Visualization',
        'Topic :: Utilities',
        'Topic :: Multimedia :: Graphics',
        'Topic :: Software Development :: User Interfaces',
        'Natural Language :: English',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
)
